## Basic Configuration

baseurl = "/" 
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jacques Serizay"
title = "Jacques Serizay"

theme = "hugo-goa"
custom_css = "css/custom.css"

## Hugo Built-in Features
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Nanogallery2
use_custom_ng2_setting = false

## Site Settings
[params]
author = "Jacques Serizay"
intro = ""
description = "Currently Post-doc at the Institut Pasteur X ENS in Paris, looking at my computer. ğŸ–¥ï¸ğŸ‡«ğŸ‡·</br></br>Previously looking at worms dancing on plates in University of Cambridge, UK. ğŸ›ğŸ‡¬ğŸ‡§</br></br>Previously looking at non-coding RNA through the microscope in the USA. ğŸ”¬ğŸ‡ºğŸ‡¸"
authorimage = "avatar.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "JS"
keywords = "developer,coding,genomics,blog,hugo"

## Social Accounts
[params.social]
github = "js2264"
linkedin = "jacquesserizay"
google = "jacquesserizay"
email = "jacquesserizay@gmail.com"

## Extras
[params.extra]
copyright = "Â© 2021. Jacques Serizay. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "publications"
    identifier = "publications"
    weight = 200
    url = "/publications/"
[[menu.main]]
    name = "coding"
    weight = 300
    identifier = "coding"
    url = "/coding/"
[[menu.main]]
    name = "blog"
    weight = 400
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "galleries"
    weight = 500
    identifier = "galleries"
    url = "/galleries/"
